# ECSE-551 Mini Project 2
Authors:
* Ashley Meagher (260822930)
* Charles Sirois (261158513)  

In [170]:
# To specify where to load the data
in_colab = False
folder_path = 'drive/MyDrive/Colab Notebooks/ECSE 551_MP2'

# imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction import text
from nltk import word_tokenize

## Load the data

In [171]:
# Load Training Data
filenames = ["train.csv", "test.csv"]

# Create class to analyze the text data
class Data:
    def __init__(self, file, train = False):
        # Download the csv data
        self.file = file
        self.data = self.readData(self.file)
        
        # Extract the subsets
        self.train = train
        self.data_list = self.data[0].to_list()
        
    # Read the data
    def readData(self, file):
        load_data = pd.read_csv(file, header = None, encoding='latin-1', skiprows=[0])
        return load_data

words_to_train = Data(filenames[0], train = True)
words_to_test = Data(filenames[1], train = False)

print(words_to_train.data_list)


["From what I have seen in my neighbourhood, too many people would rather take the chance and risk a parking ticket than pay for parking.  Two green P lots within walking distance of my street (one block and two blocks away) and everything day there's cars parked on the wrong side (it's a one way street) or blocking driveways.  If Toronto wants to raise rates, they should also consider increasing their parking enforcement efforts. \r\n\r\n\r\nFrom the article:\r\n\r\n> This fall, Toronto will launch consultations on a citywide parking strategy that could lead to changes in how much real estate the city devotes to stationary vehicles, and how much drivers pay for it.\r\n\r\n>The exercise is part of a global trend that has urban centres around the world reconsidering decades-old planning orthodoxy that dictates cities need ample and cheap parking in order to thrive. Proponents of the new philosophy argue that reducing the amount of low-cost parking frees up street space for other public 

### Format the data

In [172]:
max_features = 3000
parameters = [max_features]

In [174]:
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

class Format_data:
    def __init__(self, words_to_train, parameters):
        self.words_to_train = words_to_train
        self.features = words_to_train.data_list # word bank
        self.parameters = parameters
        self.max_feat = self.parameters[0]
        
        self.stop_words = self.stopwords()
        self.features = self.process_()

        self.vectorizer = self.count_vectorizer()
        
        
    # Create a dictionary of all words
    def count_vectorizer(self):
        vectorizer = CountVectorizer(stop_words = self.stop_words,
                                     max_features = self.max_feat, 
                                     binary = True,)
        vectors_train = vectorizer.fit_transform(self.features)

        print(vectorizer.get_feature_names_out())
        bin_values = vectors_train.todense()
        return bin_values
    
    def process_(self):
        new_data = self.punctuation()
        return new_data

    # Specify stopwords
    def stopwords(self):
        my_stop_words = stopwords.words('english') + stopwords.words('french')
        #print(my_stop_words)
        return my_stop_words

    # Remove punctuations from the dataset
    def punctuation(self):
        punctuations = "?:.,;!"
        for word in self.features:
            if word in punctuations:
                self.features.remove(word)
        
        return self.features
    
    # Remove punctuations from the dataset
    def stemming(self):
        punctuations = "?:.,;!"
        for word in self.features:
            if word in punctuations:
                self.features.remove(word)
        
        return self.features
    
    
test = Format_data(words_to_train, parameters)
print(test.vectorizer)


['000' '09' '10' ... 'époque' 'études' 'être']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
